#!/bin/bash

if [ -z "$1" ]; then
    echo "Pass python script to start_service"
    exit 1
fi

source env/bin/activate

# Redirect stdout and stderr to /dev/null or to a specific log file
nohup python "$1" > /dev/null 2>&1 &

echo "Running $1 in the background."

deactivate

